FAST/calendar/views.py
from flask import render_template, Blueprint, redirect, url_for, request, flash
from flask_login import current_user, login_required, logout_user
from FAST import app
from FAST.calendar.forms import *
from FAST.calendar.models import *
from FAST.database import *
from werkzeug.utils import secure_filename
import os
import json
from sqlalchemy.orm.attributes import flag_modified

# Registered Blueprint
calendar = Blueprint("calendar", __name__)

@calendar.route('/upload_event', methods=["GET", "POST"])
@login_required
def upload_event():
	"""
	Route to handle generation of a new Event
	"""
	form = EventForm()

	if form.validate_on_submit():
		notes = [[f.strip() for f in line.split(':')] for line in form.information.data.split('\n')]
		notes = {note[0]: ':'.join(note[1:]) for note in notes}
		print(notes)
		event = EventObject(tag=form.tag.data,
							start_time=notes["Start Time"],
					 		end_time=notes["End Time"])
		event.assign(**notes)
		event_entry = Event(name=event.tag,
							obj=event,
							user_id=current_user.id)
		db.session.add(event_entry)
		db.session.commit()

		event.__id = event_entry.id
		event_entry.obj = event
		flag_modified(event_entry, "obj")
		db.session.commit()
		form = EventForm()
		return redirect(url_for("users.view_events"))
	return render_template("upload_event.html", form=form)

@calendar.route('/download_calendar', methods=["GET", "POST"])
@login_required
def download_calendar():
	"""
	TO-DO : Implement downloading data
	"""
	return render_template("download_calendar.html")

@calendar.route('/help')
def help():
	"""
	TO-DO : Implement help dashboard
	"""
	return redirect(url_for('calendar.upload_event'))

@calendar.route('/upload_file', methods=["GET", "POST"])
@login_required
def upload_file():
	"""
	Route to handle uploading a file to generate Events
	"""
	form = UploadForm()
	if form.validate_on_submit():
		file = form.file.data
		json_data = json.loads(file.read())
		for event_data in json_data["Events"]:
			event = EventObject(
					tag=event_data["Name"],
					start_time=event_data["Start Time"],
					end_time=event_data["End Time"]
				)
			event.assign(**{key: event_data[key] for key in event_data if key not in ["Start Time", "End Time"]})
			event_entry = Event(
					name=event.tag,
					obj=event,
					user_id=current_user.id
				)
			event.__id = event_entry.id
			event_entry.obj = event
			db.session.add(event_entry)
			db.session.commit()

			event.__id = event_entry.id
			event_entry.obj = event
			flag_modified(event_entry, "obj")
			db.session.commit()

		return redirect(url_for("users.view_events"))

	return render_template("upload_file.html", form=form)

@calendar.route('/cluster/<int:calendar_id>', methods=["GET", "POST"])
@login_required
def cluster(calendar_id):
	"""
	Route to handle clustering a Calendar

	Inputs:
	- calendar_id : Int unique identifier for a Calendar entry in the database
	"""
	form = ClusterForm()
	calendar = Calendar.query.get_or_404(calendar_id)
	notes = set([note for events in calendar.obj.events.values()
					for event in events
					for note in event.notes.keys()])
	form.attribute.choices = [(note, note) for note in sorted(notes)]
	form.start.choices = [(option, option) for option in sorted(CalendarObject.KNOWN_START_BEHAVIOR)]

	if form.validate_on_submit():
		# Assign defaults
		shift = (form.shift.data if form.shift else 1)
		start = (form.start.data if form.start else "earliest")
		centers = (form.centers.data if form.centers else -1)
		obj_ = calendar.obj
		obj_.cluster(attribute=form.attribute.data,
								shift=shift,
								start=start,
								centers=centers)
		flag_modified(calendar, 'obj')
		db.session.commit()

		return redirect(url_for("users.view_calendar", calendar_id=calendar_id))

	return render_template("cluster_calendar.html", form=form, calendar=calendar.obj)

@calendar.route('/anti-cluster/<int:calendar_id>', methods=["GET", "POST"])
@login_required
def antiCluster(calendar_id):
	"""
	Route to handle anti-clustering of a Calendar

	Inputs:
	- calendar_id : Int unique identifier for a Calendar entry in the database
	"""
	form = AntiClusterForm()
	calendar = Calendar.query.get_or_404(calendar_id)
	notes = set([note for events in calendar.obj.events.values()
					for event in events
					for note in event.notes.keys()])
	form.attribute.choices = [(note, note) for note in sorted(notes)]
	form.start.choices = [(option, option) for option in sorted(CalendarObject.KNOWN_START_BEHAVIOR)]
	if form.validate_on_submit():
		# Assign defautls
		shift = (form.shift.data if form.shift else 1)
		start = (form.start.data if form.start else "earliest")
		centers = (form.centers.data if form.centers else -1)
		obj_ = calendar.obj
		obj_.antiCluster(attribute=form.attribute.data,
									shift=shift,
									start=start,
									centers=centers)

		flag_modified(calendar, 'obj')
		db.session.commit()

		return redirect(url_for("users.view_calendar", calendar_id=calendar_id))

	return render_template("anticluster_calendar.html", form=form, calendar=calendar.obj)

FAST/users/views.py
from flask import render_template, Blueprint, redirect, url_for, request, send_file
from flask_login import login_user, current_user, login_required, logout_user
from FAST import app, db
from FAST.users.forms import *
from FAST.database import *
from datetime import datetime
import json
import io
import os

users = Blueprint("users", __name__)

""" User homepage / dashboard """
@users.route('/dashboard', methods =['GET'])
@login_required
def dashboard():
    return render_template('dashboard.html')

@users.route('/logout')
@login_required
def logout():
    """
    Logout the current User
    """
    logout_user()
    return redirect(url_for("index"))

@users.route('/register', methods=["GET", "POST"])
def register():
    """
    Register a new User
    """
    form = SignupForm()

    if form.validate_on_submit():
        print(f"Registering {form.email.data}\n{form.password.data}")
        user = User(email=form.email.data,
                    password=form.password.data)

        db.session.add(user)
        db.session.commit()

        login_user(user)
        
        return redirect(url_for('index'))
    return render_template("register.html", form=form)

@users.route('/login', methods=["GET", "POST"])
def login():
    """
    Attempt to login an existing User
    """
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user is not None and user.check_password(form.password.data):
            login_user(user)
            return redirect(url_for("index"))
    return render_template("login.html", form=form)

@users.route("/view_events/")
@users.route("/view_events/<int:start_id>", methods=["GET"])
@login_required
def view_events(start_id=-1):
    """
    Collect and display all Events associated with the current User
    """
    events = Event.query.filter_by(user_id=current_user.id).order_by(Event.name.asc()).all()
    # Set first index from Calendar click-through
    if start_id == -1:
        start_id = 0
    else:
        for i, e in enumerate(events):
            if e.id == start_id:
                start_id = i
                break
    return render_template("view_events.html", events=events, len=len(events), start=start_id)

@users.route('/generate_calendar', methods=["GET", "POST"])
@login_required
def generate_calendar():
    """
    Build dashboard to handle Calendar generation
    """
    form = CalendarForm()

    if form.validate_on_submit():
        times = form.timeslots.data
        times = [line.strip() for line in times.strip().split('\n')]
        calendar = CalendarObject(tag=form.name.data, time_slots=times)
        events = [event.obj for event in Event.query.filter_by(user_id=current_user.id).all()]
        if form.heuristic.data == "rand":
            calendar.randomAssign(events)
        elif form.heuristic.data == "start":
            calendar.startTimeAssign(events)
        calendar.load(events)
        calendar_entry = Calendar(user_id=current_user.id,
                                  name=form.name.data,
                                  obj=calendar)

        db.session.add(calendar_entry)
        db.session.commit()

        return redirect(url_for("users.view_calendar", calendar_id=calendar_entry.id))
        
    return render_template("generate_calendar.html", form=form)

@users.route('/view_calendar/<int:calendar_id>', methods=["GET"])
@login_required
def view_calendar(calendar_id):
    """
    Display a Calendar object

    Inputs:
    - calendar_id : Int unique identifier for the Calendar to view
    """
    calendar = Calendar.query.get_or_404(calendar_id)
    return render_template("view_calendar.html", calendar=calendar)

@users.route('/download_data', methods=["GET"])
@login_required
def download_data():
    """
    Download all Events and Calendars for the current User as a JSON file by calling .to_json() on each object
    
    Notes:
    - For now, we will redirect to index.html. In the future, we should return to previous page
    """
    # Gather Calendars
    calendars = [cal.obj.toJson() for cal in Calendar.query.filter_by(user_id=current_user.id).all()]
    # Gather Events
    events = [event.obj.toJson() for event in Event.query.filter_by(user_id=current_user.id).all()]
    # Write to JSON
    data = {"Calendars": calendars, "Events": events}
    # Save to app.config["TEMP_DATA"] + filename
    filename = f"{current_user.email}_{datetime.now().strftime('%m_%d_%Y_%H_%M_%S')}.json"
    dirname = os.path.join(app.config["TEMP_DATA"], filename)
    with open(dirname, 'w') as file:
        json.dump(data, file)

    # Downoad JSON (name : user_email_currenttime.json)
    return_data = io.BytesIO()
    with open(dirname, 'rb') as fo:
        return_data.write(fo.read())
    return_data.seek(0)
    
    # Delete app.config["TEMP_DATA"] + filename
    os.remove(dirname)

    return send_file(return_data, mimetype='application/json',
                     attachment_filename=filename)

FAST/templates/anticluster_calendar.html
<!-- Bring in foundational interface -->
{% extends "base.html" %}
{% block content %}

<!-- Build form in a Bootstrap card -->
<div class="card">
	<div class="card-header"> Anti-Cluster {{ calendar.tag }} </div>
	<div class="card-body">
		<form method="POST" style="text-align: center;">
			{{ form.hidden_tag() }}
			<p>
				{{ form.attribute(placeholder="Attribute Name (should be Event keyword)", class="custom-form-label") }}
			</p>
			<p>
				{{ form.shift(placeholder="Number of slots between similar events", class="custom-form-label") }}
			</p>
			<p>
				{{ form.start(class="custom-form-label") }}
			</p>
			<p>
				{{ form.centers(placeholder="Number of clusters to form", class="custom-form-label") }}
			</p>
			{{ form.submit() }}
		</form>
	</div>
</div>

{% endblock %}

FAST/templates/base.html
<!-- Underlying UI -->
<html>

<header>
	<title>{{ title }}</title>
	<link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet" type="text/css">
	<script
		src="{{ url_for('static', filename='js/jquery-3.6.0.min.js') }}"></script>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
	<script type="text/javascript" src="errors.js"></script>
</header>

<body>

	<!-- load navbar -->
	{% include "navbar.html" %}
	<!-- support extended content -->
	{% block content %}{% endblock %}

</body>

</html>

FAST/templates/cluster_calendar.html
<!-- Load underlying interface -->
{% extends "base.html" %}
{% block content %}

<!-- Build form in a Bootstrap card -->
<div class="card">
	<div class="card-header"> Cluster {{ calendar.tag }} </div>
	<div class="card-body">
		<form method="POST" style="text-align: center;">
			{{ form.hidden_tag() }}
			<p>
				{{ form.attribute(placeholder="Attribute Name (should be Event keyword)", class="custom-form-label") }}
			</p>
			<p>
				{{ form.shift(placeholder="Number of slots between similar events", class="custom-form-label") }}
			</p>
			<p>
				{{ form.start(class="custom-form-label") }}
			</p>
			<p>
				{{ form.centers(placeholder="Number of clusters to form", class="custom-form-label") }}
			</p>
			{{ form.submit() }}
		</form>
	</div>
</div>

{% endblock %}

FAST/templates/data_upload.html
<!-- load underlying interface -->
{% extends "base.html" %}

<!-- Build form in a Bootstrap card -->
{% block content %}
  <div class="card">
    <div class="card-header">Upload Calendar Information</div>
    <div class="card-body">
      <form method="POST" action="/data_upload" style="text-align: center;">
        {{ form.hidden_tag() }}
        <p>
          {{ form.title(placeholder="Title", class="custom-form-label") }}
        </p>
        <p>
          {{ form.content(placeholder="Content", class="custom-form-label") }}
        </p>
        {{ form.submit() }}
      </form>
    </div>
  </div>
{% endblock %}

FAST/templates/generate_calendar.html
<!-- load underlying interface -->
{% extends "base.html" %}

<!-- Build form in a Bootstrap card -->
{% block content %}

<div class="card">
	<div class="card-header"> Generate Calendar </div>
	<div class="card-body">
		<form method="POST" style="text-align: center;">
			{{ form.hidden_tag() }}
			<p>
				{{ form.name(placeholder="Calendar Name", class="custom-form-label") }}
			</p>
			<p>
				{{ form.heuristic.label(class="custom-form-label") }}<br>{{ form.heuristic() }}
			</p>
			<p>
				{{ form.timeslots(placeholder="Time\nMM:DD:YY:HH:MM:SS", class="custom-form-label") }}
			</p>
			{{ form.submit() }}
		</form>
	</div>
</div>

{% endblock %}

FAST/templates/index.html
<!-- load underlying interface -->
{% extends "base.html" %}

{% block content %}
	<h1 class="slogan">Dynamic Schedules For Dynamic Situations</h1>
{% endblock %}

FAST/templates/login.html
<!-- load underlying interface -->
{% extends "base.html" %}

<!-- Build form in a Bootstrap card -->
{% block content %}
	<div class="card">
		<div class="card-header">Login</div>
		<div class="card-body">
			<form method="POST" style="text-align: center;">
				{{ form.hidden_tag() }}
				<p>
					{{ form.email(placeholder="Email", class="custom-form-label") }}
				</p>
				<p>
					{{ form.password(placeholder="Password", class="custom-form-label") }}
				</p>
				{{ form.submit() }}
			</form>
	</div>
		<div class="card-footer text-center"><a href="registration.hml">Don't have an account?</a></div>
	</div>
{% endblock %}

FAST/templates/navbar.html
<!-- Build navbar -->
<div class="fast-nav">
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
		<!-- TO-DO : Replace with logo -->
		<a class="navbar-brand" href="{{ url_for('index') }}">
			<img src="{{ url_for('static', filename='images/logo.jpg') }}" alt="logo" style="width:80px;height:80px;">
		</a>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navText" aria-controls="navText" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<!-- Display supported buttons -->
		<div class="collapse navbar-collapse" id="navText">
			<ul class="navbar-nav me-auto mb-2 mb-lg-0">
				<!-- <li class="nav-item">
					<a class="nav-link active" aria-current="page" href="{{ url_for('index') }}"> HOME </a>
				</li> -->
				<!-- User options -->
				{% if current_user.is_authenticated %}
					<li class="nav-item">
						<a class="nav-link" href="{{ url_for('calendar.upload_event') }}"> Create Event </a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{{ url_for('calendar.upload_file') }}"> Upload Events </a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{{ url_for('users.generate_calendar') }}"> Create Calendar </a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{{ url_for('users.view_events') }}"> View My Events </a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{{ url_for('users.download_data') }}"> Download My Data </a>
					</li>
				{% endif %}
			</ul>
			<span class="navbar-text">
				<ul class="navbar-nav me-auto mb-2 mb-lg-0">
					<!-- Non-User options -->
					{% if not current_user.is_authenticated %}
						<li class="nav-item"><a class="nav-link" href="{{ url_for('users.register') }}"> Register </a></li>
						<li class="nav-item"><a class="nav-link" href="{{ url_for('users.login') }}"> Login </a></li>
					{% endif %}
					<!-- User options -->
					{% if current_user.is_authenticated %}
						<li class="nav-item"><a class="nav-link" href="{{ url_for('users.logout') }}"> Logout </a></li>
					{% endif %}
				</ul>
			</span>
		</div>
	</nav>
</div>

FAST/templates/register.html
<!-- load underlying interface -->
{% extends "base.html" %}

<!-- Build form in a Bootstrap card -->
{% block content %}
{% if form.errors %}
	{{ form.errors }}
{% endif %}
	<div class="card">
		<div class="card-header">Registration</div>
		<div class="card-body">
			<form method="POST" style="text-align: center;">
				{{ form.hidden_tag() }}
				<p>
					{{ form.email(placeholder="Email", class="custom-form-label") }}
				</p>
				<p>
					{{ form.password(placeholder="Password", class="custom-form-label") }}
				</p>
				<p>
					{{ form.confirm(placeholder="Retype Password", class="custom-form-label") }}
				</p>
				{{ form.submit() }}
			</form>
		</div>
		<div class="card-footer text-center"><a href="login.hml">Already have an account?</a></div>
	</div>
{% endblock %}

FAST/templates/upload_event.html
<!-- load underlying interface -->
{% extends "base.html" %}

<!-- Build form in a Bootstrap card -->
{% block content %}
	<div class="card">
		<div class="card-header">Create Event</div>
		<div class="card-body">
			<form method="POST" style="text-align: center;">
				{{ form.hidden_tag() }}
				<p>
					{{ form.tag(placeholder="Tag (should be fairly unique)", style="width: 75%;", class="custom-form-label") }}
				</p>
				<p>
					{{ form.information(placeholder="Start Time: MM:DD:YY:HH:MM:SS\nEnd Time: MM:DD:YY:HH:MM:SS\nKeyword: Information about the keyword\nNote: For the time beign, \"Start Time\" and \"End Time\" are mandatory fields", style="height: 75%; width: 75%;", class="custom-form-label") }}
				</p>
				{{ form.submit() }}
			</form>
		</div>
		<div class="card-footer text-center"><a href="{{ url_for('calendar.help') }}">Questions about creating an event?</a></div>
	</div>
{% endblock %}

FAST/templates/upload_file.html
<!-- load underlying interface -->
{% extends "base.html" %}

<!-- Build form in a Bootstrap card -->
{% block content %}
	<div class="card">
		<div class="card-header">Upload Event</div>
			<form class="upload_file" action="" method="POST" enctype="multipart/form-data">
				{{ form.hidden_tag() }}
                <p>
	                {{ form.file.label(class="custom-form-label") }}{{ form.file() }}
	            </p>
            		{{ form.submit() }}
            </form>
			<div class="card-footer text-center">Please upload a JSON file</div>
	</div>
{% endblock %}

FAST/templates/view_calendar.html
<!-- load underlying interface -->
{% extends "base.html" %}

<!-- Build form in a Bootstrap card -->
{% block content %}

<div class="card">
	<div class="card-header" style="text-align: center;">{{ calendar.name }}</div>
	<div class="card-body">
		{% for time in calendar.obj.time_slots %}
			<h1 style="text-align: center;">{{ time }}</h1>
			{% for event in calendar.obj.events[time] %}
				<h3 style="text-align: center;"><a style="text-decoration: none; color: black;" href="{{ url_for('users.view_events', start_id=event.__id) }}">{{ event.tag }}</a></h3>
			{% endfor %}
		{% endfor %}
	</div>
	<div class="card-footer text-center"><a href="{{ url_for('calendar.cluster', calendar_id=calendar.id) }}">Cluster events</a><br><a href="{{ url_for('calendar.antiCluster', calendar_id=calendar.id) }}">Anti-cluster events</div>
</div>

{% endblock %}

FAST/templates/view_events.html
<!-- load underlying interface -->
{% extends "base.html" %}

<!-- Build form in a Bootstrap card -->
{% block content %}
<div class="card">
	<div class="card-body">
		<div id="EventCarousel" class="carousel slide" data-bs-ride="carousel" data-bs-interval="false">
			<div class="carousel-inner">
				{% for i in range(0,len) %}
		  			{% if i == start %}
		  				<div class="carousel-item active">
		  					<h1 style="text-align: center;">{{ events[i].name }}</h1>
		  					<h3 style="text-align: center;">{{ events[i].obj.start_time }} - {{ events[i].obj.end_time }}</h3>
		  					<p style="text-align: center;">{{ events[i].obj.notes }}</p>
		  				</div>
		  			{% else %}
		  				<div class="carousel-item">
		  					<h1 style="text-align: center;">{{ events[i].name }}</h1>
		  					<h3 style="text-align: center;">{{ events[i].obj.start_time }} - {{ events[i].obj.end_time }}</h3>
		  					<p style="text-align: center;">{{ events[i].obj.notes }}</p>
		  				</div>
		  			{% endif %}
		  		{% endfor %}
			</div>
		 	<button class="carousel-control-prev" type="button" data-bs-target="#EventCarousel" data-bs-slide="prev">
				<span class="carousel-control-prev-icon" aria-hidden="true"></span>
				<span class="visually-hidden">Previous</span>
			</button>
			<button class="carousel-control-next" type="button" data-bs-target="#EventCarousel" data-bs-slide="next">
				<span class="carousel-control-next-icon" aria-hidden="true"></span>
				<span class="visually-hidden">Next</span>
			</button>
		</div>
	</div>
</div>
{% endblock %}